### PR TITLE
Update materi.php with reusable function

### PR DESCRIPTION
**Pull request by nanto88**
hopefully this reusable function would help, thanks for review this code!

### CODE REVIEW

**Comment by msazzuhair** [comment]
I think it's also a good idea to modify the m_materi model to use reusable function too. 🤔

**Comment by syauqi** [comment]
Hi, @nanto88 .
Thank you so much for you contribution for Learnify, and I think its good idea too to make the m_matri to be reusable so i will merge your commit.
Thanks!

**Comment by nanto88** [comment]
I'm glad this update was help! 😄 
Feel free to 'beckon' me if you have another open source project to work with 😄

**Comment by nanto88** [comment]
btw @syauqi ,
would you mind to add topic this repository the "hacktoberfest" , and add label "hacktoberfest-accepted"
to more other people comes to this repository 😸

**Pull request merged**
